name: typo_tweaker
description: "Welcome to TypoTweaker - the ultimate flutter package for impressive text animations! 💬✨"
version: 0.0.1
homepage: https://github.com/zTomz/TypeTweaker

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
